from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any

class FireActivityPoint(BaseModel):
    date: str = Field(..., description="Observation date (YYYY-MM-DD)")
    detection_count: int = Field(..., description="Number of recorded satellite fire detections")
    avg_brightness_kelvin: Optional[float] = Field(None, description="Average brightness temperature in Kelvin")
    max_frp_mw: Optional[float] = Field(None, description="Maximum Fire Radiative Power (MW)")
    observation_source: str = Field("NASA FIRMS (VIIRS/MODIS)", description="Observation data source")

class EnvironmentalTrendPoint(BaseModel):
    date: str = Field(..., description="Observation date (YYYY-MM-DD)")
    temperature_2m: float = Field(..., description="Mean/Max air temperature at 2m in °C")
    relative_humidity_2m: float = Field(..., description="Mean relative humidity percentage [0-100]")
    wind_speed_10m: float = Field(..., description="Mean wind speed at 10m in km/h")
    precipitation: float = Field(0.0, description="Total precipitation in mm")
    ndvi: float = Field(0.48, description="Vegetation greenness index NDVI [-1 to 1]")
    ndmi: float = Field(-0.05, description="Canopy moisture index NDMI [-1 to 1]")

class ModelRiskTrendPoint(BaseModel):
    date: str = Field(..., description="Inference date (YYYY-MM-DD)")
    calibrated_probability: float = Field(..., description="Platt-calibrated wildfire risk probability [0-1]")
    raw_model_probability: float = Field(..., description="Uncalibrated XGBoost probability [0-1]")
    risk_category: str = Field(..., description="Low, Moderate, High, Very High")
    primary_contributor: str = Field(..., description="Top SHAP feature contributor for this date")

class CorrelationMetric(BaseModel):
    variable_x: str = Field(..., description="Independent variable name (e.g. Temperature)")
    variable_y: str = Field(..., description="Target variable name (e.g. Satellite Detections)")
    pearson_r: float = Field(..., description="Pearson correlation coefficient r [-1 to 1]")
    sample_size: int = Field(..., description="Number of aligned temporal observations")
    interpretation: str = Field(..., description="Statistically neutral interpretation")
    disclaimer: str = Field("Correlation indicates statistical co-occurrence over the selected time window and does not establish physical causation.")

class TemporalAnalysisResponse(BaseModel):
    start_date: str
    end_date: str
    total_days: int
    fire_activity_trend: List[FireActivityPoint]
    environmental_trend: List[EnvironmentalTrendPoint]
    model_risk_trend: List[ModelRiskTrendPoint]
    correlations: List[CorrelationMetric]
    temporal_coverage_notes: str
    scientific_disclaimer: str = (
        "SCIENTIFIC NOTICE: Historical fire detections represent satellite radiometer thermal anomalies from NASA FIRMS. "
        "Environmental trends describe observed meteorological/satellite parameters. Model risk values represent statistical "
        "predictions generated by the calibrated XGBoost model, not historical observations. Correlation does not establish physical causation."
    )
